export default {
    // private
    comparison: '/comparison',
    dashboard: '/dashboard',
    scenerios: '/scenerios',
    transmission: '/transmission',
    generation: '/generation',
    industrialApplications: '/industrialApplications',
    products: '/products',
    solutions: '/solutions',
    services: '/services',
    overview: '/overview',
    quickguide: '/quickguide',
    overviewTwo: '/overview/two',
    overviewThree: '/overview/three',
    categories: '/categories',
    inbox:'./inbox',
    ideas: '/ideas',
    ideasTwo: '/ideas/two',
    ideasThree: '/ideas/three',
    contacts: '/contacts',
    agents: '/agents',
    articles: '/articles',
    settings: '/settings',
    subscription: '/subscription',
    // auth
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot_password'
};
